- name: Install loadbalancer and web servers
  hosts: all
  tasks:
    - name: Install all apps server node1 and node2 (test_bransh)..
      apt:
        name: "{{ apps }}"
        state: present
        update_cache: yes
      become: true
