- name: Install loadbalancer and web servers
  hosts: all
  tasks:
    - name: Install all apps server node1 
      apt:
        name: "{{ apps }}"
        state: present
        update_cache: yes
      become: true