- name: Copy config file in load balancer
  hosts: loadbalancer
  tasks:
    - name: Upload config file in load balancer
      copy:
        src: ./config/loadbalancer.conf
        dest: /etc/apache2/sites-available/000-default.conf
        mode: 0755
      become: true