- name: Install  Two web servers
  hosts: all
  tasks:
    - name: Install all apps server node1 and node2 
      apt:
        name: "{{ apps }}"
        state: present
        update_cache: yes
      become: true
